---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-configs
  namespace: flux-system
spec:
  dependsOn:
  - name: monitoring-controller
  interval: 5m0s
  path: ./monitoring/configs
  prune: true
  sourceRef:
    kind: GitRepository
    name: monitoring
  timeout: 1m0s
  wait: true
