---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-controller
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./monitoring/controllers
  prune: true
  sourceRef:
    kind: GitRepository
    name: monitoring
